apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-dev-volume
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual-dev
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/dev"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-dev-claim
  namespace: dev
spec:
  storageClassName: manual-dev
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
