apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-prod-volume
  namespace: prod
  labels:
    type: local
spec:
  storageClassName: manual-prod
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prod"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-prod-claim
  namespace: prod
spec:
  storageClassName: manual-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
